services:
  my-server:
    image: nginx
    container_name: my-front-compose
    ports:
      - 8080:80
    depends_on:
      - api-java
    volumes:
      - type: bind
        source: ./index.html
        target: /usr/share/nginx/html/index.html
  api-java:
    build: ../8.-Network/
    container_name: my-api-java-compose
    ports:
      - 8090:8090
    depends_on:
      - db
  db:
    image: postgres
    container_name: local_pgdb_compose
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata_compose:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_compose
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pcorqui@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data_compose:/var/lib/pgadmin
volumes:
  local_pgdata_compose: null
  pgadmin-data_compose: null
# networks:
#   my-network: null
